import { Avatar } from './Avatar';

interface PodiumPlayer { id?:string;nickname:string;avatarId:string;score:number;rank:number }

const styles:Record<number,string>={1:'from-amber-100 to-amber-300 text-amber-950 min-h-64 border-amber-300',2:'from-slate-50 to-slate-200 text-slate-800 min-h-52 border-slate-200',3:'from-orange-50 to-orange-200 text-orange-950 min-h-44 border-orange-200',4:'from-violet-50 to-violet-200 text-violet-950 min-h-36 border-violet-200'};
const medals:Record<number,string>={1:'👑',2:'🥈',3:'🥉',4:'⭐'};

export function Podium({players}:{players:PodiumPlayer[]}){
  const top=players.filter((player)=>player.rank<=4).slice(0,4);
  const ordered=[top.find((p)=>p.rank===2),top.find((p)=>p.rank===1),top.find((p)=>p.rank===3),top.find((p)=>p.rank===4)].filter(Boolean) as PodiumPlayer[];
  return <div className="relative overflow-hidden rounded-[2rem] border border-violet-100 bg-gradient-to-br from-white via-violet-50 to-amber-50 px-4 py-10 text-slate-900 shadow-xl shadow-violet-100/60 sm:px-8"><div className="pointer-events-none absolute inset-0 opacity-70">{Array.from({length:24},(_,i)=><i key={i} className="confetti-piece" style={{left:`${(i*37)%100}%`,animationDelay:`-${(i%9)*.31}s`,background:['#fbbf24','#a78bfa','#34d399','#fb7185'][i%4]}}/>)}</div><div className="relative z-10 text-center"><span className="rounded-full border border-amber-200 bg-amber-50 px-4 py-2 text-xs font-black text-amber-700">اكتملت المسابقة 🎉</span><h2 className="mt-5 text-3xl font-black text-violet-950 sm:text-5xl">منصة أبطال Brio</h2><p className="mt-2 text-sm font-bold text-slate-500">تصفيق كبير لأصحاب المراكز الأولى ولكل من شارك!</p></div><div className="relative z-10 mt-10 grid grid-cols-2 items-end gap-3 sm:grid-cols-4">{ordered.map((player)=><article key={`${player.rank}-${player.nickname}`} className={`podium-rise flex flex-col items-center justify-start rounded-t-[2rem] border bg-gradient-to-b p-4 text-center shadow-lg ${styles[player.rank]||styles[4]}`}><span className="text-3xl">{medals[player.rank]}</span><Avatar src={player.avatarId} label={player.nickname} className="mt-3 h-16 w-16 rounded-2xl border-4 border-white bg-white shadow-sm"/><b className="mt-3 max-w-full truncate text-sm">{player.nickname}</b><strong className="mt-1 text-lg">{player.score.toLocaleString('ar')} نقطة</strong><span className="mt-auto pt-4 text-4xl font-black">#{player.rank}</span></article>)}</div></div>;
}
