ALTER TABLE quizzes ADD COLUMN cover_image_url TEXT;

ALTER TABLE media ADD COLUMN quiz_id TEXT;
ALTER TABLE media ADD COLUMN question_id TEXT;
ALTER TABLE media ADD COLUMN host_url TEXT;
ALTER TABLE media ADD COLUMN mobile_url TEXT;
ALTER TABLE media ADD COLUMN is_essential INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN byte_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN created_at TEXT;
